const COUNTRY_MAPPING: Record<string, string> = {
  "ROM": "Romania",
  "BHR": "Bahrain",
  "CIS": "Russia",
  "PRC": "China",
  "UK": "United Kingdom",
  "ESA": "European Space Agency",
  "ISS": "International Space Station",
  "SES": "SES S.A.",
  "SES S.A": "SES S.A.",
  "O3B": "O3b Networks",
  "ORB": "Orbcomm",
  "GLOB": "Globalstar",
  "IRID": "Iridium",
  "STAR": "Starlink",
  "ONEB": "OneWeb",
  "USA": "United States",
  "US": "United States",
  "GBR": "United Kingdom",
  "GB": "United Kingdom",
  "DEU": "Germany",
  "DE": "Germany",
  "GER": "Germany",
  "FGER": "Germany (West)",
  "FRA": "France",
  "FR": "France",
  "JPN": "Japan",
  "JP": "Japan",
  "AFG": "Afghanistan",
  "AF": "Afghanistan",
  "AGO": "Angola",
  "AO": "Angola",
  "ALB": "Albania",
  "AL": "Albania",
  "ARE": "United Arab Emirates",
  "AE": "United Arab Emirates",
  "UAE": "United Arab Emirates",
  "ARG": "Argentina",
  "AR": "Argentina",
  "ARGN": "Argentina",
  "ARM": "Armenia",
  "AM": "Armenia",
  "ATA": "Antarctica",
  "AQ": "Antarctica",
  "ATF": "Fr. S. Antarctic Lands",
  "TF": "Fr. S. Antarctic Lands",
  "AUS": "Australia",
  "AU": "Australia",
  "AUT": "Austria",
  "AT": "Austria",
  "AZE": "Azerbaijan",
  "AZ": "Azerbaijan",
  "AZER": "Azerbaijan",
  "BDI": "Burundi",
  "BI": "Burundi",
  "BEL": "Belgium",
  "BE": "Belgium",
  "BEN": "Benin",
  "BJ": "Benin",
  "BFA": "Burkina Faso",
  "BF": "Burkina Faso",
  "BGD": "Bangladesh",
  "BD": "Bangladesh",
  "BGR": "Bulgaria",
  "BG": "Bulgaria",
  "BHS": "Bahamas",
  "BS": "Bahamas",
  "BIH": "Bosnia and Herz.",
  "BA": "Bosnia and Herz.",
  "BLR": "Belarus",
  "BY": "Belarus",
  "BELA": "Belarus",
  "BLZ": "Belize",
  "BZ": "Belize",
  "BOL": "Bolivia",
  "BO": "Bolivia",
  "BRA": "Brazil",
  "BR": "Brazil",
  "BRAZ": "Brazil",
  "BRN": "Brunei",
  "BN": "Brunei",
  "BTN": "Bhutan",
  "BT": "Bhutan",
  "BWA": "Botswana",
  "BW": "Botswana",
  "CAF": "Central African Rep.",
  "CF": "Central African Rep.",
  "CAN": "Canada",
  "CA": "Canada",
  "CHE": "Switzerland",
  "CH": "Switzerland",
  "CHL": "Chile",
  "CL": "Chile",
  "CHELE": "Chile",
  "CHN": "China",
  "CN": "China",
  "CIV": "Côte d'Ivoire",
  "CI": "Côte d'Ivoire",
  "CMR": "Cameroon",
  "CM": "Cameroon",
  "COD": "Dem. Rep. Congo",
  "CD": "Dem. Rep. Congo",
  "COG": "Congo",
  "CG": "Congo",
  "COL": "Colombia",
  "CO": "Colombia",
  "CRI": "Costa Rica",
  "CR": "Costa Rica",
  "CUB": "Cuba",
  "CU": "Cuba",
  "CYP": "Cyprus",
  "CY": "Cyprus",
  "CZE": "Czechia",
  "CZ": "Czechia",
  "CZCH": "Czechia",
  "DJI": "Djibouti",
  "DJ": "Djibouti",
  "DNK": "Denmark",
  "DK": "Denmark",
  "DOM": "Dominican Rep.",
  "DO": "Dominican Rep.",
  "DZA": "Algeria",
  "DZ": "Algeria",
  "ALG": "Algeria",
  "ECU": "Ecuador",
  "EC": "Ecuador",
  "EGY": "Egypt",
  "EG": "Egypt",
  "EGPYP": "Egypt",
  "ERI": "Eritrea",
  "ER": "Eritrea",
  "ESP": "Spain",
  "ES": "Spain",
  "SPN": "Spain",
  "EST": "Estonia",
  "EE": "Estonia",
  "ETH": "Ethiopia",
  "ET": "Ethiopia",
  "FIN": "Finland",
  "FI": "Finland",
  "FJI": "Fiji",
  "FJ": "Fiji",
  "FLK": "Falkland Is.",
  "FK": "Falkland Is.",
  "GAB": "Gabon",
  "GA": "Gabon",
  "GEO": "Georgia",
  "GE": "Georgia",
  "GHA": "Ghana",
  "GH": "Ghana",
  "GIN": "Guinea",
  "GN": "Guinea",
  "GMB": "Gambia",
  "GM": "Gambia",
  "GNB": "Guinea-Bissau",
  "GW": "Guinea-Bissau",
  "GNQ": "Eq. Guinea",
  "GQ": "Eq. Guinea",
  "GRC": "Greece",
  "GR": "Greece",
  "GREC": "Greece",
  "GRL": "Greenland",
  "GL": "Greenland",
  "GTM": "Guatemala",
  "GT": "Guatemala",
  "GUY": "Guyana",
  "GY": "Guyana",
  "HND": "Honduras",
  "HN": "Honduras",
  "HRV": "Croatia",
  "HR": "Croatia",
  "HTI": "Haiti",
  "HT": "Haiti",
  "HUN": "Hungary",
  "HU": "Hungary",
  "IDN": "Indonesia",
  "ID": "Indonesia",
  "INDO": "Indonesia",
  "IND": "India",
  "IN": "India",
  "IRL": "Ireland",
  "IE": "Ireland",
  "IRN": "Iran",
  "IR": "Iran",
  "IRQ": "Iraq",
  "IQ": "Iraq",
  "IRAW": "Iran/Iraq",
  "ISL": "Iceland",
  "IS": "Iceland",
  "ISR": "Israel",
  "IL": "Israel",
  "ISRA": "Israel",
  "ITA": "Italy",
  "IT": "Italy",
  "JAM": "Jamaica",
  "JM": "Jamaica",
  "JOR": "Jordan",
  "JO": "Jordan",
  "KAZ": "Kazakhstan",
  "KZ": "Kazakhstan",
  "KEN": "Kenya",
  "KE": "Kenya",
  "KGZ": "Kyrgyzstan",
  "KG": "Kyrgyzstan",
  "KHM": "Cambodia",
  "KH": "Cambodia",
  "KOR": "South Korea",
  "KR": "South Korea",
  "SKOR": "South Korea",
  "XK": "Kosovo",
  "KWT": "Kuwait",
  "KW": "Kuwait",
  "LAO": "Laos",
  "LA": "Laos",
  "LAOS": "Laos",
  "LBN": "Lebanon",
  "LB": "Lebanon",
  "LBR": "Liberia",
  "LR": "Liberia",
  "LBY": "Libya",
  "LY": "Libya",
  "LKA": "Sri Lanka",
  "LK": "Sri Lanka",
  "LSO": "Lesotho",
  "LS": "Lesotho",
  "LTU": "Lithuania",
  "LT": "Lithuania",
  "LUX": "Luxembourg",
  "LU": "Luxembourg",
  "LUXE": "Luxembourg",
  "LVA": "Latvia",
  "LV": "Latvia",
  "MAR": "Morocco",
  "MA": "Morocco",
  "MDA": "Moldova",
  "MD": "Moldova",
  "MDG": "Madagascar",
  "MG": "Madagascar",
  "MEX": "Mexico",
  "MX": "Mexico",
  "MKD": "Macedonia",
  "MK": "Macedonia",
  "MLI": "Mali",
  "ML": "Mali",
  "MMR": "Myanmar",
  "MM": "Myanmar",
  "MNE": "Montenegro",
  "ME": "Montenegro",
  "MNG": "Mongolia",
  "MN": "Mongolia",
  "MOZ": "Mozambique",
  "MZ": "Mozambique",
  "MRT": "Mauritania",
  "MR": "Mauritania",
  "MWI": "Malawi",
  "MW": "Malawi",
  "MYS": "Malaysia",
  "MY": "Malaysia",
  "MALA": "Malaysia",
  "NAM": "Namibia",
  "NA": "Namibia",
  "NCL": "New Caledonia",
  "NC": "New Caledonia",
  "NER": "Niger",
  "NE": "Niger",
  "NGA": "Nigeria",
  "NG": "Nigeria",
  "NIC": "Nicaragua",
  "NI": "Nicaragua",
  "NLD": "Netherlands",
  "NL": "Netherlands",
  "NETH": "Netherlands",
  "NPL": "Nepal",
  "NP": "Nepal",
  "NZL": "New Zealand",
  "NZ": "New Zealand",
  "OMN": "Oman",
  "OM": "Oman",
  "PAK": "Pakistan",
  "PK": "Pakistan",
  "PAKI": "Pakistan",
  "PAN": "Panama",
  "PA": "Panama",
  "PER": "Peru",
  "PE": "Peru",
  "PHL": "Philippines",
  "PH": "Philippines",
  "RP": "Philippines",
  "PNG": "Papua New Guinea",
  "PG": "Papua New Guinea",
  "POL": "Poland",
  "PL": "Poland",
  "PRI": "Puerto Rico",
  "PR": "Puerto Rico",
  "PRK": "North Korea",
  "KP": "North Korea",
  "NKOR": "North Korea",
  "PRT": "Portugal",
  "PT": "Portugal",
  "POR": "Portugal",
  "PRY": "Paraguay",
  "PY": "Paraguay",
  "PSE": "Palestine",
  "PS": "Palestine",
  "QAT": "Qatar",
  "QA": "Qatar",
  "ROU": "Romania",
  "RO": "Romania",
  "RUS": "Russia",
  "RU": "Russia",
  "RWA": "Rwanda",
  "RW": "Rwanda",
  "ESH": "W. Sahara",
  "EH": "W. Sahara",
  "SAU": "Saudi Arabia",
  "SA": "Saudi Arabia",
  "SAUD": "Saudi Arabia",
  "SDN": "Sudan",
  "SD": "Sudan",
  "SSD": "S. Sudan",
  "SS": "S. Sudan",
  "SEN": "Senegal",
  "SN": "Senegal",
  "SLB": "Solomon Is.",
  "SB": "Solomon Is.",
  "SLE": "Sierra Leone",
  "SL": "Sierra Leone",
  "SLV": "El Salvador",
  "SV": "El Salvador",
  "SOM": "Somalia",
  "SO": "Somalia",
  "SRB": "Serbia",
  "RS": "Serbia",
  "SUR": "Suriname",
  "SR": "Suriname",
  "SVK": "Slovakia",
  "SK": "Slovakia",
  "SVN": "Slovenia",
  "SI": "Slovenia",
  "SWE": "Sweden",
  "SE": "Sweden",
  "SWED": "Sweden",
  "SWZ": "Swaziland",
  "SZ": "Swaziland",
  "SYR": "Syria",
  "SY": "Syria",
  "TCD": "Chad",
  "TD": "Chad",
  "TGO": "Togo",
  "TG": "Togo",
  "THA": "Thailand",
  "TH": "Thailand",
  "THAI": "Thailand",
  "TJK": "Tajikistan",
  "TJ": "Tajikistan",
  "TKM": "Turkmenistan",
  "TM": "Turkmenistan",
  "TLS": "Timor-Leste",
  "TL": "Timor-Leste",
  "TTO": "Trinidad and Tobago",
  "TT": "Trinidad and Tobago",
  "TUN": "Tunisia",
  "TN": "Tunisia",
  "TUR": "Turkey",
  "TR": "Turkey",
  "TURK": "Turkey",
  "TWN": "Taiwan",
  "TW": "Taiwan",
  "TZA": "Tanzania",
  "TZ": "Tanzania",
  "UGA": "Uganda",
  "UG": "Uganda",
  "UKR": "Ukraine",
  "UA": "Ukraine",
  "URY": "Uruguay",
  "UY": "Uruguay",
  "UZB": "Uzbekistan",
  "UZ": "Uzbekistan",
  "VEN": "Venezuela",
  "VE": "Venezuela",
  "VENZ": "Venezuela",
  "VNM": "Vietnam",
  "VN": "Vietnam",
  "VTNM": "Vietnam",
  "VUT": "Vanuatu",
  "VU": "Vanuatu",
  "YEM": "Yemen",
  "YE": "Yemen",
  "ZAF": "South Africa",
  "ZA": "South Africa",
  "SAFR": "South Africa",
  "ZMB": "Zambia",
  "ZM": "Zambia",
  "ZWE": "Zimbabwe",
  "ZW": "Zimbabwe",
  "ITSO": "Intl. Telecom. Satellite Org.",
  "EUTE": "Eutelsat",
  "EUME": "EUMETSAT",
  "SEAL": "Sea Launch",
  "AB": "Arabsat",
  "ABS": "Asia Broadcast Satellite",
  "ASRA": "AsiaSat",
  "RASC": "Rascom",
  "CHBZ": "China/Brazil",
  "BNIG": "Belarus/Nigeria",
  "STCT": "Singapore/Taiwan",
  "NICO": "Nigeria/China",
  "USBZ": "USA/Brazil",
  "FRIT": "France/Italy",
  "TMMC": "Turkmenistan/Monaco",
  "DEB": "Debris",
  "SING": "Singapore"
};

export const getCountryName = (code: string): string => {
  if (!code || code === '-') return '';

  const countries = code.split(/[,/]/);
  const result = countries.map(c => {
    const trimmed = c.trim();
    if (!trimmed) return null;
    const up = trimmed.toUpperCase();
    if (COUNTRY_MAPPING[up]) return COUNTRY_MAPPING[up];

    if (trimmed.length === 2) {
      try {
        const displayNames = new Intl.DisplayNames(['en'], { type: 'region' });
        const name = displayNames.of(up);
        if (name && name !== up) return name;
      } catch {
        // Fallback to code
      }
    }
    return trimmed;
  }).filter(Boolean);

  return result.join(code.includes('/') ? ' / ' : ', ');
};

export const getSingleCountryName = (code: string): string => {
  const up = code.trim().toUpperCase();
  if (!up || up === '-') return '';

  if (COUNTRY_MAPPING[up]) return COUNTRY_MAPPING[up];

  if (up.length === 2) {
    try {
      const displayNames = new Intl.DisplayNames(['en'], { type: 'region' });
      const name = displayNames.of(up);
      if (name && name !== up) return name;
    } catch {
      // Fallback to code
    }
  }

  return up;
};
